---
- name: Remove AnyLog
  hosts: vm
  become: yes
  vars_files:
    - defaults.yaml
  tasks:
    - name: Check if directory exists from older deployment
      stat:
        path: "{{ repo_local_dir_path }}"
      register: anylog_dir

    - name: Remove AnyLog
      ansible.builtin.shell: |
        cd "{{ repo_local_dir_path }}"
        sudo make down ANYLOG_TYPE=generic
      args:
        executable: /bin/bash
      when: anylog_dir.stat.exists and anylog_dir.stat.isdir
      register: output
    
    - name: Print output
      debug:
        var: output.stdout
      when: anylog_dir.stat.exists and anylog_dir.stat.isdir
    
    - name: Print message when directory doesn't exist
      debug:
        msg: |
          The dir "{{ repo_local_dir_path }}" doesn't exist.
      when: not (anylog_dir.stat.exists and anylog_dir.stat.isdir)

    - name: Print validation successful message
      debug:
        msg: "AnyLog Removal Successful"
      when: anylog_dir.stat.exists and anylog_dir.stat.isdir