network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp-identifier: mac
      dhcp4: {{ use_dhcp }}
      {% if not use_dhcp %}
      addresses:
      - {{ static_ip }}
      gateway4: {{ gateway }}
      nameservers:
        addresses: {{ dns }}
      {% endif %}
    enp2s0:
      dhcp4: true
      dhcp4-overrides:
        use-routes: false